spring:
  application:
    name: Enterprice level todo
    # Database connection settings
  datasource:
      url: jdbc:postgresql://localhost:5432/todo_db
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver

      hikari:
        maximum-pool-size: 20
        minimum-idle: 5
      # JPA configuration 
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # liquibase migration stuff
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  secret: mysupersecretkeymysupersecretkey123456mysupersecretkeymysupersecretkey123456mysupersecretkeymysupersecretkey123456
  access-token-expiration: 900000     # should be 10-15 minutes
  refresh-token-expiration: 604800000  # should be 1-30 days 
  issuer: todo-app   

 # Logging level config
# logging:
#   level:
#     org:
#       springframework: DEBUG
#     com:
#       lakshman: DEBUG

  # later we will replace these values with the environment variable names
